//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AplikacjaDoTranspozycji
{
    using System;
    using System.Collections.ObjectModel;
    using System.ComponentModel.DataAnnotations;

    public partial class ChordSongs
    {
        [Key]
        public int ChordID { get; set; }
        public Nullable<int> UserID { get; set; }
        public string Title { get; set; }
        public string Chord { get; set; }
    
        public virtual Users Users { get; set; }
    }
}
